### PR TITLE
feat: add a new app-badge imageset

### PR DESCRIPTION
**Pull request by notlee**

### CODE REVIEW

**Comment by notlee** [comment]
Since you offered @sjparkinson I wouldn't mind a review on this! 🙏 🙇 This PR adds an `app-badge` image set. Turns out it's a fairly combersum process to add a new image set to the Image Service.  

Here's the dev app...
Imageset preview: https://origami-image-service-dev.herokuapp.com/__origami/service/image/v2/docs/image-sets#App-Badge
Example image: https://origami-image-service-dev.herokuapp.com/__origami/service/image/v2/images/raw/app-badge-v1:apple?source=origami-image-service-website
Imageset details: https://origami-image-service-dev.herokuapp.com/__origami/service/image/v2/imagesets/app-badge?source=origami-image-service

**Comment by notlee** [comment]
FYI the CSS file moves [because of this PR](https://github.com/Financial-Times/origami-image-service/pull/787), it's currently 404ing in prod. Apologies for not splitting into 2 commits.

**Comment by sjparkinson** [comment]
> FYI the CSS file moves [because of this PR](https://github.com/Financial-Times/origami-image-service/pull/787), it's currently 404ing in prod. Apologies for not splitting into 2 commits.

Literally the only thing I was trying to work out about in looking through the code, you read my mind.

**Review by sjparkinson — APPROVED** [review]
Looks good. I've just searched for fticon in the repo to see if there might be other places to include appBadge, found maybe two places:

* https://cs.github.com/Financial-Times/origami-image-service/blob/4193731247110f6d9e6b4812dff0550217b9baa5/test/integration/v2/images-debug.test.js#L14
* https://cs.github.com/Financial-Times/origami-image-service/blob/4193731247110f6d9e6b4812dff0550217b9baa5/lib/routes/v2/docs/url-builder.js#L77

**Comment by notlee** [comment]
Thanks @sjparkinson 🙇 

1. Most of those properties weren't used in those tests, including fticon. Copy-pasted test fixtures I think. I've moved them to their own file.
2. Good spot. That's for the example image sets in the [url builder](https://origami-image-service-dev.herokuapp.com/__origami/service/image/v2/docs/url-builder?url=app-badge-v1%3Aapple&preview=true). I've updated that to include the app badge and a couple of other image sets too. 🎉 

Will go ahead and merge if tests pass.

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v453.2.0 :tada:

**Pull request merged**
